[package]
name = "cv-template"
version = "0.1.0"
authors = ["tsnobip <https://github.com/tsnobip>"]
license = "MIT"
description = "A stylish and customizable cv template for Typst, designed with elegant typographic variations. Based on tsnobips template <https://github.com/tsnobip/typst-typographic-resume>"
categories = ["cv"]
keywords = [
  "CV",
  "Curriculum Vitae",
  "Resume",
  "Minimal",
  "Typographic",
  "Professional",
]
repository = "https://github.com/tuxerator/cv-template"
exclude = ["*.pdf", "profile_pic_example.jpg"]
entrypoint = "package.typ"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"
